name: Restart and Retrain Model on Push

on:
  push:
    branches:
      - main

jobs:
  deploy-and-retrain:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: SSH into the server to restart Docker containers
      - name: SSH into server and restart Docker containers
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/mlops_project_Meguebli
            docker-compose down
            docker-compose up -d --build  # Rebuild locally instead of pulling from Docker Hub

      # Step 3: Trigger retraining by calling the FastAPI /retrain endpoint
      - name: Trigger retraining
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.RETRAIN_TOKEN }}" \
            -H "Content-Type: application/json" \
            https://62d2-165-50-3-88.ngrok-free.app/retrain
        env:
          RETRAIN_TOKEN: ${{ secrets.RETRAIN_TOKEN }}